os: linux
dist: trusty
language: python
python: 2.7

addons:
  apt:
    packages:
    - protobuf-compiler
    - python-protobuf
    - build-essential

before_install:
  - virtualenv venv
  - source venv/bin/activate

install:
  - pip install -U pip
  - pip install setuptools_trial
  - pip install -r requirements.txt
  - pip install .

script:
  - trial tests

