os: linux
dist: trusty
language: python
python: 2.7

notifications:
  slack:
    secure: e3AXBz8BpviMD/dEtMIBcn7WHpiXUpn2JUDnPDICdaFli2KOdXAwkX1Wh0DWkwfWYEcGvJU2oDjjxPxkPnO16pxXfn87854onRVLzMO20UoegnJvUXPr3BKtclWHZcGdb/4gq+YFXlA4e3zNb8MWYeymE3UuabWqRGwIH2CydS7TaSRdwavNi83FqRQRhWL6GV2NMQKAMldC0QKJYcnK3MRoaV63FnQ5tdyiBZ0AnRNr/CNWNRl8yoU9uQhlKeTX5OEdqSEKM11YFGJVQfoQpxnPGFZVUfOr6mIkVxG+EYV2GdIsOkJOiLjBjHOUC9cOMcootfYxApu+/vaGruFvlYhUQZoYAwjKhL4dxiRFhntgsy/WFCWkHSDQ7TAs/DBAUQds8ZQiy9yBYapPEk/OXmVpGxJ6Wc+ku7u+MOM+7mR6oL6B6IzeZJ+Jvrz0d+5e43kaTot4oOlwdjxC89UstJfbg3ns/Z+6G7mVIQhhUmqTsdtGtxdEEILiPkRgwKaYKGb4qDii82S6XZ0PdmB7TUXoind0RekK6y+ylcxc3zohfvzniueY7Z5giFQNkCOZdMqxaziNBHUyTSU0xoHbRlvMQbumiZ7j1vTvPNLnpwoxZsqJBVgSye9Cq8/40aj6JK6lGGGkQyI5Ays84eQjBGSTZj6RbTxWZzri7SZ8QOk=

addons:
  apt:
    packages:
    - protobuf-compiler
    - python-protobuf
    - build-essential

before_install:
  - virtualenv venv
  - source venv/bin/activate
  - protoc --proto_path=./lbryschema/proto --python_out=./lbryschema/schema ./lbryschema/proto/*.proto

install:
  - pip install -U pip
  - pip install setuptools_trial
  - pip install -r requirements.txt
  - pip install .

script:
  - trial tests
