os: linux
dist: trusty
language: python
python: 2.7

notifications:
  slack:
    secure: "FSpfMxyr3JFfogPPTi4b08MQemqvjUjIgwepyLvwL1dinIzi0FrUBokZV98eXuaa3B2NDQe7Und1wzOKfe4nB+b7/HPH+a3R2HKVpz3ltmwILCZUJfKVSH6BXn9CXTHRW9H0WPz4IqHVAEhyg24LYhFRfjFZwAsa97UBRj/9arQbeENRFUjudT/HIdgbk5zA57DRukjXbwkEt2j9GxZYvp6q3+K8lzgOhCeuqg9SMvVUZ5UV5M+bPkYVGlShbBKEwFUrBDRjNU9BRU/cdYv/JiG2p3iMqmx0jg6eRqPXENkidUmON1cp7fjZyaVjB5AhYQ0HhM94UTwvgXMlICsZ78tCwi6vuoY/RvdEOSfR7MIxTYwkaxGc6ExnJs41mouIEvCs6FLOPH+4b9EeNJDNYgT3dqDUtIPTJFVptWGUz1C0J4i3PWgNVAC5P8irxOqk7A4id0DQrw0Orm8qK3W5eABrBtbZ0LNAv0JxRPlVgVGx5+N0uCWidxJ5wbY9dqce6PXmR66ShoqN3rwJ+CL3MRXE6TCnNCSgERIxE4BQzjVmDSGScDyDSFVeW9nA+sGchtODEDK1MpbmUckLpkZnnBA8naPWAwhJkuwyPK/qBmfohrapy9+2J9kkwqhJE7e/Xo4Flc8l+oVkyFucc93IKXP/VF6UkfwbdZcxBFhGK5s="

addons:
  apt:
    packages:
    - protobuf-compiler
    - python-protobuf
    - build-essential

before_install:
  - virtualenv venv
  - source venv/bin/activate
  - protoc --proto_path=./lbryschema/proto --python_out=./lbryschema/schema ./lbryschema/proto/*.proto

install:
  - pip install -U pip
  - pip install setuptools_trial
  - pip install -r requirements.txt
  - pip install .

script:
  - trial tests

